version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soder
      MONGO_INITDB_ROOT_PASSWORD: soder1989

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: soder
      ME_CONFIG_MONGODB_ADMINPASSWORD: soder1989
      ME_CONFIG_MONGODB_URL: mongodb://soder:soder1989@mongo:27017/